name: Vue Front Build Push

# 1. 이벤트 트리거(on)
on:
  push:
    branches: [ main ]

# 2. Jobs - runner
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 3. source checkout
      - name: Source Checkout
        uses: actions/checkout@v2

      # 4. setup node
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'
          distribution: 'adopt'

      # 5. docker buildx
      # runner(ubuntu) docker buildx install
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v2

      # 6. docker login
      # docker login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. docker build and push
      # docker image build to push to docker hub
      - name: Push Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          # DOCKER BUILD -T JIHWANB/IMAG/TAGS
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vueapp:${{ github.sha }}
          platforms: linux/amd64, linux/arm64

      # 파이프라인 작성이 끝나면 로컬 콘솔에서 이미지 빌드 , 실행
      # docker build ~~~~
      # docker run port(8080:8080) container_name image